// @generated
// This file was automatically generated and should not be edited.

import ApolloAPI

public protocol SelectionSet: ApolloAPI.SelectionSet & ApolloAPI.RootSelectionSet
where Schema == GitHubAPIGraphQL.SchemaMetadata {}

public protocol InlineFragment: ApolloAPI.SelectionSet & ApolloAPI.InlineFragment
where Schema == GitHubAPIGraphQL.SchemaMetadata {}

public protocol MutableSelectionSet: ApolloAPI.MutableRootSelectionSet
where Schema == GitHubAPIGraphQL.SchemaMetadata {}

public protocol MutableInlineFragment: ApolloAPI.MutableSelectionSet & ApolloAPI.InlineFragment
where Schema == GitHubAPIGraphQL.SchemaMetadata {}

public enum SchemaMetadata: ApolloAPI.SchemaMetadata {
  public static let configuration: any ApolloAPI.SchemaConfiguration.Type = SchemaConfiguration.self

  public static func objectType(forTypename typename: String) -> ApolloAPI.Object? {
    switch typename {
    case "AddedToMergeQueueEvent": return GitHubAPIGraphQL.Objects.AddedToMergeQueueEvent
    case "AddedToProjectEvent": return GitHubAPIGraphQL.Objects.AddedToProjectEvent
    case "App": return GitHubAPIGraphQL.Objects.App
    case "AssignedEvent": return GitHubAPIGraphQL.Objects.AssignedEvent
    case "AutoMergeDisabledEvent": return GitHubAPIGraphQL.Objects.AutoMergeDisabledEvent
    case "AutoMergeEnabledEvent": return GitHubAPIGraphQL.Objects.AutoMergeEnabledEvent
    case "AutoRebaseEnabledEvent": return GitHubAPIGraphQL.Objects.AutoRebaseEnabledEvent
    case "AutoSquashEnabledEvent": return GitHubAPIGraphQL.Objects.AutoSquashEnabledEvent
    case "AutomaticBaseChangeFailedEvent": return GitHubAPIGraphQL.Objects.AutomaticBaseChangeFailedEvent
    case "AutomaticBaseChangeSucceededEvent": return GitHubAPIGraphQL.Objects.AutomaticBaseChangeSucceededEvent
    case "BaseRefChangedEvent": return GitHubAPIGraphQL.Objects.BaseRefChangedEvent
    case "BaseRefDeletedEvent": return GitHubAPIGraphQL.Objects.BaseRefDeletedEvent
    case "BaseRefForcePushedEvent": return GitHubAPIGraphQL.Objects.BaseRefForcePushedEvent
    case "Blob": return GitHubAPIGraphQL.Objects.Blob
    case "Bot": return GitHubAPIGraphQL.Objects.Bot
    case "BranchProtectionRule": return GitHubAPIGraphQL.Objects.BranchProtectionRule
    case "BypassForcePushAllowance": return GitHubAPIGraphQL.Objects.BypassForcePushAllowance
    case "BypassPullRequestAllowance": return GitHubAPIGraphQL.Objects.BypassPullRequestAllowance
    case "CWE": return GitHubAPIGraphQL.Objects.CWE
    case "CheckRun": return GitHubAPIGraphQL.Objects.CheckRun
    case "CheckSuite": return GitHubAPIGraphQL.Objects.CheckSuite
    case "ClosedEvent": return GitHubAPIGraphQL.Objects.ClosedEvent
    case "CodeOfConduct": return GitHubAPIGraphQL.Objects.CodeOfConduct
    case "CommentDeletedEvent": return GitHubAPIGraphQL.Objects.CommentDeletedEvent
    case "Commit": return GitHubAPIGraphQL.Objects.Commit
    case "CommitComment": return GitHubAPIGraphQL.Objects.CommitComment
    case "CommitCommentThread": return GitHubAPIGraphQL.Objects.CommitCommentThread
    case "Comparison": return GitHubAPIGraphQL.Objects.Comparison
    case "ConnectedEvent": return GitHubAPIGraphQL.Objects.ConnectedEvent
    case "ConvertToDraftEvent": return GitHubAPIGraphQL.Objects.ConvertToDraftEvent
    case "ConvertedNoteToIssueEvent": return GitHubAPIGraphQL.Objects.ConvertedNoteToIssueEvent
    case "ConvertedToDiscussionEvent": return GitHubAPIGraphQL.Objects.ConvertedToDiscussionEvent
    case "CrossReferencedEvent": return GitHubAPIGraphQL.Objects.CrossReferencedEvent
    case "DemilestonedEvent": return GitHubAPIGraphQL.Objects.DemilestonedEvent
    case "DependabotUpdate": return GitHubAPIGraphQL.Objects.DependabotUpdate
    case "DependencyGraphManifest": return GitHubAPIGraphQL.Objects.DependencyGraphManifest
    case "DeployKey": return GitHubAPIGraphQL.Objects.DeployKey
    case "DeployedEvent": return GitHubAPIGraphQL.Objects.DeployedEvent
    case "Deployment": return GitHubAPIGraphQL.Objects.Deployment
    case "DeploymentEnvironmentChangedEvent": return GitHubAPIGraphQL.Objects.DeploymentEnvironmentChangedEvent
    case "DeploymentReview": return GitHubAPIGraphQL.Objects.DeploymentReview
    case "DeploymentStatus": return GitHubAPIGraphQL.Objects.DeploymentStatus
    case "DisconnectedEvent": return GitHubAPIGraphQL.Objects.DisconnectedEvent
    case "Discussion": return GitHubAPIGraphQL.Objects.Discussion
    case "DiscussionCategory": return GitHubAPIGraphQL.Objects.DiscussionCategory
    case "DiscussionComment": return GitHubAPIGraphQL.Objects.DiscussionComment
    case "DiscussionPoll": return GitHubAPIGraphQL.Objects.DiscussionPoll
    case "DiscussionPollOption": return GitHubAPIGraphQL.Objects.DiscussionPollOption
    case "DraftIssue": return GitHubAPIGraphQL.Objects.DraftIssue
    case "Enterprise": return GitHubAPIGraphQL.Objects.Enterprise
    case "EnterpriseAdministratorInvitation": return GitHubAPIGraphQL.Objects.EnterpriseAdministratorInvitation
    case "EnterpriseIdentityProvider": return GitHubAPIGraphQL.Objects.EnterpriseIdentityProvider
    case "EnterpriseMemberInvitation": return GitHubAPIGraphQL.Objects.EnterpriseMemberInvitation
    case "EnterpriseRepositoryInfo": return GitHubAPIGraphQL.Objects.EnterpriseRepositoryInfo
    case "EnterpriseServerInstallation": return GitHubAPIGraphQL.Objects.EnterpriseServerInstallation
    case "EnterpriseServerUserAccount": return GitHubAPIGraphQL.Objects.EnterpriseServerUserAccount
    case "EnterpriseServerUserAccountEmail": return GitHubAPIGraphQL.Objects.EnterpriseServerUserAccountEmail
    case "EnterpriseServerUserAccountsUpload": return GitHubAPIGraphQL.Objects.EnterpriseServerUserAccountsUpload
    case "EnterpriseUserAccount": return GitHubAPIGraphQL.Objects.EnterpriseUserAccount
    case "Environment": return GitHubAPIGraphQL.Objects.Environment
    case "ExternalIdentity": return GitHubAPIGraphQL.Objects.ExternalIdentity
    case "Gist": return GitHubAPIGraphQL.Objects.Gist
    case "GistComment": return GitHubAPIGraphQL.Objects.GistComment
    case "HeadRefDeletedEvent": return GitHubAPIGraphQL.Objects.HeadRefDeletedEvent
    case "HeadRefForcePushedEvent": return GitHubAPIGraphQL.Objects.HeadRefForcePushedEvent
    case "HeadRefRestoredEvent": return GitHubAPIGraphQL.Objects.HeadRefRestoredEvent
    case "IpAllowListEntry": return GitHubAPIGraphQL.Objects.IpAllowListEntry
    case "Issue": return GitHubAPIGraphQL.Objects.Issue
    case "IssueComment": return GitHubAPIGraphQL.Objects.IssueComment
    case "IssueType": return GitHubAPIGraphQL.Objects.IssueType
    case "IssueTypeAddedEvent": return GitHubAPIGraphQL.Objects.IssueTypeAddedEvent
    case "IssueTypeChangedEvent": return GitHubAPIGraphQL.Objects.IssueTypeChangedEvent
    case "IssueTypeRemovedEvent": return GitHubAPIGraphQL.Objects.IssueTypeRemovedEvent
    case "Label": return GitHubAPIGraphQL.Objects.Label
    case "LabeledEvent": return GitHubAPIGraphQL.Objects.LabeledEvent
    case "Language": return GitHubAPIGraphQL.Objects.Language
    case "LanguageConnection": return GitHubAPIGraphQL.Objects.LanguageConnection
    case "LanguageEdge": return GitHubAPIGraphQL.Objects.LanguageEdge
    case "License": return GitHubAPIGraphQL.Objects.License
    case "LinkedBranch": return GitHubAPIGraphQL.Objects.LinkedBranch
    case "LockedEvent": return GitHubAPIGraphQL.Objects.LockedEvent
    case "Mannequin": return GitHubAPIGraphQL.Objects.Mannequin
    case "MarkedAsDuplicateEvent": return GitHubAPIGraphQL.Objects.MarkedAsDuplicateEvent
    case "MarketplaceCategory": return GitHubAPIGraphQL.Objects.MarketplaceCategory
    case "MarketplaceListing": return GitHubAPIGraphQL.Objects.MarketplaceListing
    case "MemberFeatureRequestNotification": return GitHubAPIGraphQL.Objects.MemberFeatureRequestNotification
    case "MembersCanDeleteReposClearAuditEntry": return GitHubAPIGraphQL.Objects.MembersCanDeleteReposClearAuditEntry
    case "MembersCanDeleteReposDisableAuditEntry": return GitHubAPIGraphQL.Objects.MembersCanDeleteReposDisableAuditEntry
    case "MembersCanDeleteReposEnableAuditEntry": return GitHubAPIGraphQL.Objects.MembersCanDeleteReposEnableAuditEntry
    case "MentionedEvent": return GitHubAPIGraphQL.Objects.MentionedEvent
    case "MergeQueue": return GitHubAPIGraphQL.Objects.MergeQueue
    case "MergeQueueEntry": return GitHubAPIGraphQL.Objects.MergeQueueEntry
    case "MergedEvent": return GitHubAPIGraphQL.Objects.MergedEvent
    case "MigrationSource": return GitHubAPIGraphQL.Objects.MigrationSource
    case "Milestone": return GitHubAPIGraphQL.Objects.Milestone
    case "MilestonedEvent": return GitHubAPIGraphQL.Objects.MilestonedEvent
    case "MovedColumnsInProjectEvent": return GitHubAPIGraphQL.Objects.MovedColumnsInProjectEvent
    case "OIDCProvider": return GitHubAPIGraphQL.Objects.OIDCProvider
    case "OauthApplicationCreateAuditEntry": return GitHubAPIGraphQL.Objects.OauthApplicationCreateAuditEntry
    case "OrgAddBillingManagerAuditEntry": return GitHubAPIGraphQL.Objects.OrgAddBillingManagerAuditEntry
    case "OrgAddMemberAuditEntry": return GitHubAPIGraphQL.Objects.OrgAddMemberAuditEntry
    case "OrgBlockUserAuditEntry": return GitHubAPIGraphQL.Objects.OrgBlockUserAuditEntry
    case "OrgConfigDisableCollaboratorsOnlyAuditEntry": return GitHubAPIGraphQL.Objects.OrgConfigDisableCollaboratorsOnlyAuditEntry
    case "OrgConfigEnableCollaboratorsOnlyAuditEntry": return GitHubAPIGraphQL.Objects.OrgConfigEnableCollaboratorsOnlyAuditEntry
    case "OrgCreateAuditEntry": return GitHubAPIGraphQL.Objects.OrgCreateAuditEntry
    case "OrgDisableOauthAppRestrictionsAuditEntry": return GitHubAPIGraphQL.Objects.OrgDisableOauthAppRestrictionsAuditEntry
    case "OrgDisableSamlAuditEntry": return GitHubAPIGraphQL.Objects.OrgDisableSamlAuditEntry
    case "OrgDisableTwoFactorRequirementAuditEntry": return GitHubAPIGraphQL.Objects.OrgDisableTwoFactorRequirementAuditEntry
    case "OrgEnableOauthAppRestrictionsAuditEntry": return GitHubAPIGraphQL.Objects.OrgEnableOauthAppRestrictionsAuditEntry
    case "OrgEnableSamlAuditEntry": return GitHubAPIGraphQL.Objects.OrgEnableSamlAuditEntry
    case "OrgEnableTwoFactorRequirementAuditEntry": return GitHubAPIGraphQL.Objects.OrgEnableTwoFactorRequirementAuditEntry
    case "OrgInviteMemberAuditEntry": return GitHubAPIGraphQL.Objects.OrgInviteMemberAuditEntry
    case "OrgInviteToBusinessAuditEntry": return GitHubAPIGraphQL.Objects.OrgInviteToBusinessAuditEntry
    case "OrgOauthAppAccessApprovedAuditEntry": return GitHubAPIGraphQL.Objects.OrgOauthAppAccessApprovedAuditEntry
    case "OrgOauthAppAccessBlockedAuditEntry": return GitHubAPIGraphQL.Objects.OrgOauthAppAccessBlockedAuditEntry
    case "OrgOauthAppAccessDeniedAuditEntry": return GitHubAPIGraphQL.Objects.OrgOauthAppAccessDeniedAuditEntry
    case "OrgOauthAppAccessRequestedAuditEntry": return GitHubAPIGraphQL.Objects.OrgOauthAppAccessRequestedAuditEntry
    case "OrgOauthAppAccessUnblockedAuditEntry": return GitHubAPIGraphQL.Objects.OrgOauthAppAccessUnblockedAuditEntry
    case "OrgRemoveBillingManagerAuditEntry": return GitHubAPIGraphQL.Objects.OrgRemoveBillingManagerAuditEntry
    case "OrgRemoveMemberAuditEntry": return GitHubAPIGraphQL.Objects.OrgRemoveMemberAuditEntry
    case "OrgRemoveOutsideCollaboratorAuditEntry": return GitHubAPIGraphQL.Objects.OrgRemoveOutsideCollaboratorAuditEntry
    case "OrgRestoreMemberAuditEntry": return GitHubAPIGraphQL.Objects.OrgRestoreMemberAuditEntry
    case "OrgRestoreMemberMembershipOrganizationAuditEntryData": return GitHubAPIGraphQL.Objects.OrgRestoreMemberMembershipOrganizationAuditEntryData
    case "OrgRestoreMemberMembershipRepositoryAuditEntryData": return GitHubAPIGraphQL.Objects.OrgRestoreMemberMembershipRepositoryAuditEntryData
    case "OrgRestoreMemberMembershipTeamAuditEntryData": return GitHubAPIGraphQL.Objects.OrgRestoreMemberMembershipTeamAuditEntryData
    case "OrgUnblockUserAuditEntry": return GitHubAPIGraphQL.Objects.OrgUnblockUserAuditEntry
    case "OrgUpdateDefaultRepositoryPermissionAuditEntry": return GitHubAPIGraphQL.Objects.OrgUpdateDefaultRepositoryPermissionAuditEntry
    case "OrgUpdateMemberAuditEntry": return GitHubAPIGraphQL.Objects.OrgUpdateMemberAuditEntry
    case "OrgUpdateMemberRepositoryCreationPermissionAuditEntry": return GitHubAPIGraphQL.Objects.OrgUpdateMemberRepositoryCreationPermissionAuditEntry
    case "OrgUpdateMemberRepositoryInvitationPermissionAuditEntry": return GitHubAPIGraphQL.Objects.OrgUpdateMemberRepositoryInvitationPermissionAuditEntry
    case "Organization": return GitHubAPIGraphQL.Objects.Organization
    case "OrganizationIdentityProvider": return GitHubAPIGraphQL.Objects.OrganizationIdentityProvider
    case "OrganizationInvitation": return GitHubAPIGraphQL.Objects.OrganizationInvitation
    case "OrganizationMigration": return GitHubAPIGraphQL.Objects.OrganizationMigration
    case "Package": return GitHubAPIGraphQL.Objects.Package
    case "PackageFile": return GitHubAPIGraphQL.Objects.PackageFile
    case "PackageTag": return GitHubAPIGraphQL.Objects.PackageTag
    case "PackageVersion": return GitHubAPIGraphQL.Objects.PackageVersion
    case "PageInfo": return GitHubAPIGraphQL.Objects.PageInfo
    case "ParentIssueAddedEvent": return GitHubAPIGraphQL.Objects.ParentIssueAddedEvent
    case "ParentIssueRemovedEvent": return GitHubAPIGraphQL.Objects.ParentIssueRemovedEvent
    case "PinnedDiscussion": return GitHubAPIGraphQL.Objects.PinnedDiscussion
    case "PinnedEnvironment": return GitHubAPIGraphQL.Objects.PinnedEnvironment
    case "PinnedEvent": return GitHubAPIGraphQL.Objects.PinnedEvent
    case "PinnedIssue": return GitHubAPIGraphQL.Objects.PinnedIssue
    case "PrivateRepositoryForkingDisableAuditEntry": return GitHubAPIGraphQL.Objects.PrivateRepositoryForkingDisableAuditEntry
    case "PrivateRepositoryForkingEnableAuditEntry": return GitHubAPIGraphQL.Objects.PrivateRepositoryForkingEnableAuditEntry
    case "Project": return GitHubAPIGraphQL.Objects.Project
    case "ProjectCard": return GitHubAPIGraphQL.Objects.ProjectCard
    case "ProjectColumn": return GitHubAPIGraphQL.Objects.ProjectColumn
    case "ProjectV2": return GitHubAPIGraphQL.Objects.ProjectV2
    case "ProjectV2Field": return GitHubAPIGraphQL.Objects.ProjectV2Field
    case "ProjectV2Item": return GitHubAPIGraphQL.Objects.ProjectV2Item
    case "ProjectV2ItemFieldDateValue": return GitHubAPIGraphQL.Objects.ProjectV2ItemFieldDateValue
    case "ProjectV2ItemFieldIterationValue": return GitHubAPIGraphQL.Objects.ProjectV2ItemFieldIterationValue
    case "ProjectV2ItemFieldNumberValue": return GitHubAPIGraphQL.Objects.ProjectV2ItemFieldNumberValue
    case "ProjectV2ItemFieldSingleSelectValue": return GitHubAPIGraphQL.Objects.ProjectV2ItemFieldSingleSelectValue
    case "ProjectV2ItemFieldTextValue": return GitHubAPIGraphQL.Objects.ProjectV2ItemFieldTextValue
    case "ProjectV2IterationField": return GitHubAPIGraphQL.Objects.ProjectV2IterationField
    case "ProjectV2SingleSelectField": return GitHubAPIGraphQL.Objects.ProjectV2SingleSelectField
    case "ProjectV2StatusUpdate": return GitHubAPIGraphQL.Objects.ProjectV2StatusUpdate
    case "ProjectV2View": return GitHubAPIGraphQL.Objects.ProjectV2View
    case "ProjectV2Workflow": return GitHubAPIGraphQL.Objects.ProjectV2Workflow
    case "PublicKey": return GitHubAPIGraphQL.Objects.PublicKey
    case "PullRequest": return GitHubAPIGraphQL.Objects.PullRequest
    case "PullRequestCommit": return GitHubAPIGraphQL.Objects.PullRequestCommit
    case "PullRequestCommitCommentThread": return GitHubAPIGraphQL.Objects.PullRequestCommitCommentThread
    case "PullRequestReview": return GitHubAPIGraphQL.Objects.PullRequestReview
    case "PullRequestReviewComment": return GitHubAPIGraphQL.Objects.PullRequestReviewComment
    case "PullRequestReviewThread": return GitHubAPIGraphQL.Objects.PullRequestReviewThread
    case "PullRequestThread": return GitHubAPIGraphQL.Objects.PullRequestThread
    case "Push": return GitHubAPIGraphQL.Objects.Push
    case "PushAllowance": return GitHubAPIGraphQL.Objects.PushAllowance
    case "Query": return GitHubAPIGraphQL.Objects.Query
    case "Reaction": return GitHubAPIGraphQL.Objects.Reaction
    case "ReadyForReviewEvent": return GitHubAPIGraphQL.Objects.ReadyForReviewEvent
    case "Ref": return GitHubAPIGraphQL.Objects.Ref
    case "ReferencedEvent": return GitHubAPIGraphQL.Objects.ReferencedEvent
    case "Release": return GitHubAPIGraphQL.Objects.Release
    case "ReleaseAsset": return GitHubAPIGraphQL.Objects.ReleaseAsset
    case "RemovedFromMergeQueueEvent": return GitHubAPIGraphQL.Objects.RemovedFromMergeQueueEvent
    case "RemovedFromProjectEvent": return GitHubAPIGraphQL.Objects.RemovedFromProjectEvent
    case "RenamedTitleEvent": return GitHubAPIGraphQL.Objects.RenamedTitleEvent
    case "ReopenedEvent": return GitHubAPIGraphQL.Objects.ReopenedEvent
    case "RepoAccessAuditEntry": return GitHubAPIGraphQL.Objects.RepoAccessAuditEntry
    case "RepoAddMemberAuditEntry": return GitHubAPIGraphQL.Objects.RepoAddMemberAuditEntry
    case "RepoAddTopicAuditEntry": return GitHubAPIGraphQL.Objects.RepoAddTopicAuditEntry
    case "RepoArchivedAuditEntry": return GitHubAPIGraphQL.Objects.RepoArchivedAuditEntry
    case "RepoChangeMergeSettingAuditEntry": return GitHubAPIGraphQL.Objects.RepoChangeMergeSettingAuditEntry
    case "RepoConfigDisableAnonymousGitAccessAuditEntry": return GitHubAPIGraphQL.Objects.RepoConfigDisableAnonymousGitAccessAuditEntry
    case "RepoConfigDisableCollaboratorsOnlyAuditEntry": return GitHubAPIGraphQL.Objects.RepoConfigDisableCollaboratorsOnlyAuditEntry
    case "RepoConfigDisableContributorsOnlyAuditEntry": return GitHubAPIGraphQL.Objects.RepoConfigDisableContributorsOnlyAuditEntry
    case "RepoConfigDisableSockpuppetDisallowedAuditEntry": return GitHubAPIGraphQL.Objects.RepoConfigDisableSockpuppetDisallowedAuditEntry
    case "RepoConfigEnableAnonymousGitAccessAuditEntry": return GitHubAPIGraphQL.Objects.RepoConfigEnableAnonymousGitAccessAuditEntry
    case "RepoConfigEnableCollaboratorsOnlyAuditEntry": return GitHubAPIGraphQL.Objects.RepoConfigEnableCollaboratorsOnlyAuditEntry
    case "RepoConfigEnableContributorsOnlyAuditEntry": return GitHubAPIGraphQL.Objects.RepoConfigEnableContributorsOnlyAuditEntry
    case "RepoConfigEnableSockpuppetDisallowedAuditEntry": return GitHubAPIGraphQL.Objects.RepoConfigEnableSockpuppetDisallowedAuditEntry
    case "RepoConfigLockAnonymousGitAccessAuditEntry": return GitHubAPIGraphQL.Objects.RepoConfigLockAnonymousGitAccessAuditEntry
    case "RepoConfigUnlockAnonymousGitAccessAuditEntry": return GitHubAPIGraphQL.Objects.RepoConfigUnlockAnonymousGitAccessAuditEntry
    case "RepoCreateAuditEntry": return GitHubAPIGraphQL.Objects.RepoCreateAuditEntry
    case "RepoDestroyAuditEntry": return GitHubAPIGraphQL.Objects.RepoDestroyAuditEntry
    case "RepoRemoveMemberAuditEntry": return GitHubAPIGraphQL.Objects.RepoRemoveMemberAuditEntry
    case "RepoRemoveTopicAuditEntry": return GitHubAPIGraphQL.Objects.RepoRemoveTopicAuditEntry
    case "Repository": return GitHubAPIGraphQL.Objects.Repository
    case "RepositoryConnection": return GitHubAPIGraphQL.Objects.RepositoryConnection
    case "RepositoryInvitation": return GitHubAPIGraphQL.Objects.RepositoryInvitation
    case "RepositoryMigration": return GitHubAPIGraphQL.Objects.RepositoryMigration
    case "RepositoryRule": return GitHubAPIGraphQL.Objects.RepositoryRule
    case "RepositoryRuleset": return GitHubAPIGraphQL.Objects.RepositoryRuleset
    case "RepositoryRulesetBypassActor": return GitHubAPIGraphQL.Objects.RepositoryRulesetBypassActor
    case "RepositoryTopic": return GitHubAPIGraphQL.Objects.RepositoryTopic
    case "RepositoryVisibilityChangeDisableAuditEntry": return GitHubAPIGraphQL.Objects.RepositoryVisibilityChangeDisableAuditEntry
    case "RepositoryVisibilityChangeEnableAuditEntry": return GitHubAPIGraphQL.Objects.RepositoryVisibilityChangeEnableAuditEntry
    case "RepositoryVulnerabilityAlert": return GitHubAPIGraphQL.Objects.RepositoryVulnerabilityAlert
    case "ReviewDismissalAllowance": return GitHubAPIGraphQL.Objects.ReviewDismissalAllowance
    case "ReviewDismissedEvent": return GitHubAPIGraphQL.Objects.ReviewDismissedEvent
    case "ReviewRequest": return GitHubAPIGraphQL.Objects.ReviewRequest
    case "ReviewRequestRemovedEvent": return GitHubAPIGraphQL.Objects.ReviewRequestRemovedEvent
    case "ReviewRequestedEvent": return GitHubAPIGraphQL.Objects.ReviewRequestedEvent
    case "SavedReply": return GitHubAPIGraphQL.Objects.SavedReply
    case "SearchResultItemConnection": return GitHubAPIGraphQL.Objects.SearchResultItemConnection
    case "SearchResultItemEdge": return GitHubAPIGraphQL.Objects.SearchResultItemEdge
    case "SecurityAdvisory": return GitHubAPIGraphQL.Objects.SecurityAdvisory
    case "SponsorsActivity": return GitHubAPIGraphQL.Objects.SponsorsActivity
    case "SponsorsListing": return GitHubAPIGraphQL.Objects.SponsorsListing
    case "SponsorsListingFeaturedItem": return GitHubAPIGraphQL.Objects.SponsorsListingFeaturedItem
    case "SponsorsTier": return GitHubAPIGraphQL.Objects.SponsorsTier
    case "Sponsorship": return GitHubAPIGraphQL.Objects.Sponsorship
    case "SponsorshipNewsletter": return GitHubAPIGraphQL.Objects.SponsorshipNewsletter
    case "StarredRepositoryConnection": return GitHubAPIGraphQL.Objects.StarredRepositoryConnection
    case "Status": return GitHubAPIGraphQL.Objects.Status
    case "StatusCheckRollup": return GitHubAPIGraphQL.Objects.StatusCheckRollup
    case "StatusContext": return GitHubAPIGraphQL.Objects.StatusContext
    case "SubIssueAddedEvent": return GitHubAPIGraphQL.Objects.SubIssueAddedEvent
    case "SubIssueRemovedEvent": return GitHubAPIGraphQL.Objects.SubIssueRemovedEvent
    case "SubscribedEvent": return GitHubAPIGraphQL.Objects.SubscribedEvent
    case "Tag": return GitHubAPIGraphQL.Objects.Tag
    case "Team": return GitHubAPIGraphQL.Objects.Team
    case "TeamAddMemberAuditEntry": return GitHubAPIGraphQL.Objects.TeamAddMemberAuditEntry
    case "TeamAddRepositoryAuditEntry": return GitHubAPIGraphQL.Objects.TeamAddRepositoryAuditEntry
    case "TeamChangeParentTeamAuditEntry": return GitHubAPIGraphQL.Objects.TeamChangeParentTeamAuditEntry
    case "TeamDiscussion": return GitHubAPIGraphQL.Objects.TeamDiscussion
    case "TeamDiscussionComment": return GitHubAPIGraphQL.Objects.TeamDiscussionComment
    case "TeamRemoveMemberAuditEntry": return GitHubAPIGraphQL.Objects.TeamRemoveMemberAuditEntry
    case "TeamRemoveRepositoryAuditEntry": return GitHubAPIGraphQL.Objects.TeamRemoveRepositoryAuditEntry
    case "Topic": return GitHubAPIGraphQL.Objects.Topic
    case "TransferredEvent": return GitHubAPIGraphQL.Objects.TransferredEvent
    case "Tree": return GitHubAPIGraphQL.Objects.Tree
    case "UnassignedEvent": return GitHubAPIGraphQL.Objects.UnassignedEvent
    case "UnlabeledEvent": return GitHubAPIGraphQL.Objects.UnlabeledEvent
    case "UnlockedEvent": return GitHubAPIGraphQL.Objects.UnlockedEvent
    case "UnmarkedAsDuplicateEvent": return GitHubAPIGraphQL.Objects.UnmarkedAsDuplicateEvent
    case "UnpinnedEvent": return GitHubAPIGraphQL.Objects.UnpinnedEvent
    case "UnsubscribedEvent": return GitHubAPIGraphQL.Objects.UnsubscribedEvent
    case "User": return GitHubAPIGraphQL.Objects.User
    case "UserBlockedEvent": return GitHubAPIGraphQL.Objects.UserBlockedEvent
    case "UserContentEdit": return GitHubAPIGraphQL.Objects.UserContentEdit
    case "UserList": return GitHubAPIGraphQL.Objects.UserList
    case "UserNamespaceRepository": return GitHubAPIGraphQL.Objects.UserNamespaceRepository
    case "UserStatus": return GitHubAPIGraphQL.Objects.UserStatus
    case "VerifiableDomain": return GitHubAPIGraphQL.Objects.VerifiableDomain
    case "Workflow": return GitHubAPIGraphQL.Objects.Workflow
    case "WorkflowRun": return GitHubAPIGraphQL.Objects.WorkflowRun
    case "WorkflowRunFile": return GitHubAPIGraphQL.Objects.WorkflowRunFile
    default: return nil
    }
  }
}

public enum Objects {}
public enum Interfaces {}
public enum Unions {}
