//
//  Repo+sampleData.swift
//  iOSEngineerCodeCheck
//
//  Created by HIROKI IKEUCHI on 2022/11/13.
//  Copyright © 2022 YUMEMI Inc. All rights reserved.
//

import Foundation

extension Repo {
    
    static let sampleDataWithLongWord: Repo =
        .init(id: 44838949,
              name: "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789",
              fullName: "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789/ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789",
              owner:
                User(id: 10639145,
                     name: "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789",
                     avatarImagePath: "https://avatars.githubusercontent.com/u/10639145?v=4",
                     htmlPath: "https://github.com/apple/ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"),
              starsCount: 61080,
              watchersCount: 2100,
              forksCount: 9815,
              openIssuesCount: 6175,
              language: "C++",
              htmlPath: "https://github.com/apple/swift/ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789",
              websitePath: "https://www.swift.org/ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789",
              description: String(repeating: "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789", count: 5),
              subscribersCount: 2508)
            
    static let sampleDataWithoutSomeInfo: Repo =
        .init(id: 44838949,
              name: "swift",
              fullName: "apple/swift",
              owner:
                User(id: 10639145,
                     name: "apple",
                     avatarImagePath: "https://avatars.githubusercontent.com/u/10639145?v=4",
                     htmlPath: "https://github.com/apple"),
              starsCount: 61308,
              watchersCount: 61308,
              forksCount: 9858,
              openIssuesCount: 6244,
              language: nil,
              htmlPath: "https://github.com/apple/swift",
              websitePath: nil,
              description: nil,
              subscribersCount: 0)

    static let sampleDataForReposCellSkelton = Repo(
        id: 44838949,
        name: "Lorem ipsum dol",
        fullName: "apple/swift",
        owner:
            User(id: 10639145,
                 name: "Lorem ipsum",
                 avatarImagePath: "",
                 htmlPath: "https://github.com/apple"),
        starsCount: 61308,
        watchersCount: 61308,
        forksCount: 9858,
        openIssuesCount: 6244,
        language: "",
        htmlPath: "https://github.com/apple/swift",
        websitePath: "https://swift.org",
        description: """
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. 
Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
""",
        subscribersCount: 0
    )
    
    static let sampleData: [Repo] = [
        .init(id: 44838949,
              name: "swift",
              fullName: "apple/swift",
              owner:
                User(id: 10639145,
                     name: "apple",
                     avatarImagePath: "https://avatars.githubusercontent.com/u/10639145?v=4",
                     htmlPath: "https://github.com/apple"),
              starsCount: 61308,
              watchersCount: 61308,
              forksCount: 9858,
              openIssuesCount: 6244,
              language: "C++",
              htmlPath: "https://github.com/apple/swift",
              websitePath: "https://swift.org",
              description: "The Swift Programming Language",
              subscribersCount: 0),
        .init(id: 790019,
              name: "swift",
              fullName: "openstack/swift",
              owner:
                User(id: 324574,
                     name: "openstack",
                     avatarImagePath: "https://avatars.githubusercontent.com/u/324574?v=4",
                     htmlPath: "https://github.com/openstack"),
              starsCount: 2356,
              watchersCount: 2356,
              forksCount: 1058,
              openIssuesCount: 0,
              language: "Python",
              htmlPath: "https://github.com/openstack/swift",
              websitePath: "https://opendev.org/openstack/swift",
              description: "OpenStack Storage (Swift). Mirror of code maintained at opendev.org.",
              subscribersCount: 0),
        .init(id: 130902948,
              name: "swift",
              fullName: "tensorflow/swift",
              owner:
                User(id: 15658638,
                     name: "tensorflow",
                     avatarImagePath: "https://avatars.githubusercontent.com/u/15658638?v=4",
                     htmlPath: "https://github.com/tensorflow"),
              starsCount: 6072,
              watchersCount: 6072,
              forksCount: 621,
              openIssuesCount: 37,
              language: "Jupyter Notebook",
              htmlPath: "https://github.com/tensorflow/swift",
              websitePath: "https://tensorflow.org/swift",
              description: "Swift for TensorFlow",
              subscribersCount: 0),
        .init(id: 20965586,
              name: "SwiftyJSON",
              fullName: "SwiftyJSON/SwiftyJSON",
              owner:
                User(id: 8858017,
                     name: "SwiftyJSON",
                     avatarImagePath: "https://avatars.githubusercontent.com/u/8858017?v=4",
                     htmlPath: "https://github.com/SwiftyJSON"),
              starsCount: 21671,
              watchersCount: 21671,
              forksCount: 3364,
              openIssuesCount: 128,
              language: "Swift",
              htmlPath: "https://github.com/SwiftyJSON/SwiftyJSON",
              websitePath: "",
              description: "The better way to deal with JSON data in Swift.",
              subscribersCount: 0),
        .init(id: 20822291,
              name: "SwiftGuide",
              fullName: "ipader/SwiftGuide",
              owner:
                User(id: 373016,
                     name: "ipader",
                     avatarImagePath: "https://avatars.githubusercontent.com/u/373016?v=4",
                     htmlPath: "https://github.com/ipader"),
              starsCount: 15787,
              watchersCount: 15787,
              forksCount: 3631,
              openIssuesCount: 0,
              language: "Swift",
              htmlPath: "https://github.com/ipader/SwiftGuide",
              websitePath: "",
              description: "Swift Featured Projects in brain Mapping",
              subscribersCount: 0),
        .init(id: 64705781,
              name: "SwifterSwift",
              fullName: "SwifterSwift/SwifterSwift",
              owner:
                User(id: 25029478,
                     name: "SwifterSwift",
                     avatarImagePath: "https://avatars.githubusercontent.com/u/25029478?v=4",
                     htmlPath: "https://github.com/SwifterSwift"),
              starsCount: 11952,
              watchersCount: 11952,
              forksCount: 1486,
              openIssuesCount: 21,
              language: "Swift",
              htmlPath: "https://github.com/SwifterSwift/SwifterSwift",
              websitePath: "https://swifterswift.com",
              description: "A handy collection of more than 500 native Swift extensions to boost your productivity.",
              subscribersCount: 0),
        .init(id: 35732214,
              name: "SwiftLint",
              fullName: "realm/SwiftLint",
              owner:
                User(id: 7575099,
                     name: "realm",
                     avatarImagePath: "https://avatars.githubusercontent.com/u/7575099?v=4",
                     htmlPath: "https://github.com/realm"),
              starsCount: 16827,
              watchersCount: 16827,
              forksCount: 2015,
              openIssuesCount: 350,
              language: "Swift",
              htmlPath: "https://github.com/realm/SwiftLint",
              websitePath: "https://realm.github.io/SwiftLint",
              description: "A tool to enforce Swift style and conventions.",
              subscribersCount: 0),
        .init(id: 94066125,
              name: "Swift",
              fullName: "iOS-Swift-Developers/Swift",
              owner:
                User(id: 27724501,
                     name: "iOS-Swift-Developers",
                     avatarImagePath: "https://avatars.githubusercontent.com/u/27724501?v=4",
                     htmlPath: "https://github.com/iOS-Swift-Developers"),
              starsCount: 1625,
              watchersCount: 1625,
              forksCount: 441,
              openIssuesCount: 9,
              language: "C",
              htmlPath: "https://github.com/iOS-Swift-Developers/Swift",
              websitePath: "http://blog.csdn.net/qq_31810357",
              description: "🥇Swift基础知识大全,🚀Swift学习从简单到复杂,不断地完善与更新, 欢迎Star❤️,欢迎Fork, iOS开发者交流:①群:446310206 ②群:426087546",
              subscribersCount: 0),
        .init(id: 63729462,
              name: "swift",
              fullName: "airbnb/swift",
              owner:
                User(id: 698437,
                     name: "airbnb",
                     avatarImagePath: "https://avatars.githubusercontent.com/u/698437?v=4",
                     htmlPath: "https://github.com/airbnb"),
              starsCount: 1761,
              watchersCount: 1761,
              forksCount: 273,
              openIssuesCount: 0,
              language: "Markdown",
              htmlPath: "https://github.com/airbnb/swift",
              websitePath: "",
              description: "Airbnb's Swift Style Guide",
              subscribersCount: 0),
        .init(id: 27896005,
              name: "Swift",
              fullName: "jaguar07/Swift",
              owner:
                User(id: 5323134,
                     name: "jaguar07",
                     avatarImagePath: "https://avatars.githubusercontent.com/u/5323134?v=4",
                     htmlPath: "https://github.com/jaguar07"),
              starsCount: 62,
              watchersCount: 62,
              forksCount: 1084,
              openIssuesCount: 0,
              language: "Swift",
              htmlPath: "https://github.com/jaguar07/Swift",
              websitePath: "",
              description: "Sample Code",
              subscribersCount: 0),
        .init(id: 4276357,
              name: "swift",
              fullName: "facebookarchive/swift",
              owner:
                User(id: 7560860,
                     name: "facebookarchive",
                     avatarImagePath: "https://avatars.githubusercontent.com/u/7560860?v=4",
                     htmlPath: "https://github.com/facebookarchive"),
              starsCount: 885,
              watchersCount: 885,
              forksCount: 316,
              openIssuesCount: 0,
              language: "Java",
              htmlPath: "https://github.com/facebookarchive/swift",
              websitePath: "",
              description: "An annotation-based Java library for creating Thrift serializable types and services.",
              subscribersCount: 0),
        .init(id: 33569135,
              name: "RxSwift",
              fullName: "ReactiveX/RxSwift",
              owner:
                User(id: 6407041,
                     name: "ReactiveX",
                     avatarImagePath: "https://avatars.githubusercontent.com/u/6407041?v=4",
                     htmlPath: "https://github.com/ReactiveX"),
              starsCount: 22975,
              watchersCount: 22975,
              forksCount: 4031,
              openIssuesCount: 19,
              language: "Swift",
              htmlPath: "https://github.com/ReactiveX/RxSwift",
              websitePath: "",
              description: "Reactive Programming in Swift",
              subscribersCount: 0),
        .init(id: 22458259,
              name: "Alamofire",
              fullName: "Alamofire/Alamofire",
              owner:
                User(id: 7774181,
                     name: "Alamofire",
                     avatarImagePath: "https://avatars.githubusercontent.com/u/7774181?v=4",
                     htmlPath: "https://github.com/Alamofire"),
              starsCount: 38675,
              watchersCount: 38675,
              forksCount: 7308,
              openIssuesCount: 37,
              language: "Swift",
              htmlPath: "https://github.com/Alamofire/Alamofire",
              websitePath: "",
              description: "Elegant HTTP Networking in Swift",
              subscribersCount: 0),
        .init(id: 20682114,
              name: "SwiftLanguageWeather",
              fullName: "JakeLin/SwiftLanguageWeather",
              owner:
                User(id: 573856,
                     name: "JakeLin",
                     avatarImagePath: "https://avatars.githubusercontent.com/u/573856?v=4",
                     htmlPath: "https://github.com/JakeLin"),
              starsCount: 5207,
              watchersCount: 5207,
              forksCount: 1219,
              openIssuesCount: 9,
              language: "Swift",
              htmlPath: "https://github.com/JakeLin/SwiftLanguageWeather",
              websitePath: "",
              description: "Swift Language Weather is an iOS weather app developed in Swift 4. ",
              subscribersCount: 0),
        .init(id: 35143711,
              name: "SwiftDate",
              fullName: "malcommac/SwiftDate",
              owner:
                User(id: 235645,
                     name: "malcommac",
                     avatarImagePath: "https://avatars.githubusercontent.com/u/235645?v=4",
                     htmlPath: "https://github.com/malcommac"),
              starsCount: 7157,
              watchersCount: 7157,
              forksCount: 712,
              openIssuesCount: 72,
              language: "Swift",
              htmlPath: "https://github.com/malcommac/SwiftDate",
              websitePath: "",
              description: "🐔 Toolkit to parse, validate, manipulate, compare and display dates, time & timezones in Swift.",
              subscribersCount: 0),
        .init(id: 65219683,
              name: "SwiftMessages",
              fullName: "SwiftKickMobile/SwiftMessages",
              owner:
                User(id: 13121066,
                     name: "SwiftKickMobile",
                     avatarImagePath: "https://avatars.githubusercontent.com/u/13121066?v=4",
                     htmlPath: "https://github.com/SwiftKickMobile"),
              starsCount: 6700,
              watchersCount: 6700,
              forksCount: 714,
              openIssuesCount: 46,
              language: "Swift",
              htmlPath: "https://github.com/SwiftKickMobile/SwiftMessages",
              websitePath: "",
              description: "A very flexible message bar for iOS written in Swift.",
              subscribersCount: 0),
        .init(id: 39166950,
              name: "SwiftGen",
              fullName: "SwiftGen/SwiftGen",
              owner:
                User(id: 24867377,
                     name: "SwiftGen",
                     avatarImagePath: "https://avatars.githubusercontent.com/u/24867377?v=4",
                     htmlPath: "https://github.com/SwiftGen"),
              starsCount: 8322,
              watchersCount: 8322,
              forksCount: 659,
              openIssuesCount: 71,
              language: "Swift",
              htmlPath: "https://github.com/SwiftGen/SwiftGen",
              websitePath: "",
              description: "The Swift code generator for your assets, storyboards, Localizable.strings, … — Get rid of all String-based APIs!",
              subscribersCount: 0),
        .init(id: 21696302,
              name: "awesome-swift",
              fullName: "matteocrippa/awesome-swift",
              owner:
                User(id: 475463,
                     name: "matteocrippa",
                     avatarImagePath: "https://avatars.githubusercontent.com/u/475463?v=4",
                     htmlPath: "https://github.com/matteocrippa"),
              starsCount: 22747,
              watchersCount: 22747,
              forksCount: 3026,
              openIssuesCount: 2,
              language: "Ruby",
              htmlPath: "https://github.com/matteocrippa/awesome-swift",
              websitePath: "",
              description: "A collaborative list of awesome Swift libraries and resources. Feel free to contribute!",
              subscribersCount: 0),
        .init(id: 50447720,
              name: "swift-algorithm-club",
              fullName: "kodecocodes/swift-algorithm-club",
              owner:
                User(id: 4722515,
                     name: "kodecocodes",
                     avatarImagePath: "https://avatars.githubusercontent.com/u/4722515?v=4",
                     htmlPath: "https://github.com/kodecocodes"),
              starsCount: 27173,
              watchersCount: 27173,
              forksCount: 4873,
              openIssuesCount: 56,
              language: "Swift",
              htmlPath: "https://github.com/kodecocodes/swift-algorithm-club",
              websitePath: "",
              description: "Algorithms and data structures in Swift, with explanations!",
              subscribersCount: 0),
        .init(id: 41854508,
              name: "SwiftyStoreKit",
              fullName: "bizz84/SwiftyStoreKit",
              owner:
                User(id: 153167,
                     name: "bizz84",
                     avatarImagePath: "https://avatars.githubusercontent.com/u/153167?v=4",
                     htmlPath: "https://github.com/bizz84"),
              starsCount: 6139,
              watchersCount: 6139,
              forksCount: 732,
              openIssuesCount: 167,
              language: "Swift",
              htmlPath: "https://github.com/bizz84/SwiftyStoreKit",
              websitePath: "",
              description: "Lightweight In App Purchases Swift framework for iOS 8.0+, tvOS 9.0+ and macOS 10.10+ ⛺",
              subscribersCount: 0),
        .init(id: 66302557,
              name: "SwiftFormat",
              fullName: "nicklockwood/SwiftFormat",
              owner:
                User(id: 546885,
                     name: "nicklockwood",
                     avatarImagePath: "https://avatars.githubusercontent.com/u/546885?v=4",
                     htmlPath: "https://github.com/nicklockwood"),
              starsCount: 6284,
              watchersCount: 6284,
              forksCount: 509,
              openIssuesCount: 204,
              language: "Swift",
              htmlPath: "https://github.com/nicklockwood/SwiftFormat",
              websitePath: "",
              description: "A command-line tool and Xcode Extension for formatting Swift code",
              subscribersCount: 0),
        .init(id: 190707613,
              name: "About-SwiftUI",
              fullName: "Juanpe/About-SwiftUI",
              owner:
                User(id: 1409041,
                     name: "Juanpe",
                     avatarImagePath: "https://avatars.githubusercontent.com/u/1409041?v=4",
                     htmlPath: "https://github.com/Juanpe"),
              starsCount: 6443,
              watchersCount: 6443,
              forksCount: 644,
              openIssuesCount: 7,
              language: "Swift",
              htmlPath: "https://github.com/Juanpe/About-SwiftUI",
              websitePath: "https://juanpe.github.io/About-SwiftUI",
              description: "Gathering all info published, both by Apple and by others, about new framework SwiftUI. ",
              subscribersCount: 0),
        .init(id: 20430314,
              name: "FlappySwift",
              fullName: "fullstackio/FlappySwift",
              owner:
                User(id: 4064333,
                     name: "fullstackio",
                     avatarImagePath: "https://avatars.githubusercontent.com/u/4064333?v=4",
                     htmlPath: "https://github.com/fullstackio"),
              starsCount: 9517,
              watchersCount: 9517,
              forksCount: 2655,
              openIssuesCount: 14,
              language: "Swift",
              htmlPath: "https://github.com/fullstackio/FlappySwift",
              websitePath: "https://www.fullstackedu.com",
              description: "swift implementation of flappy bird. More at fullstackedu.com",
              subscribersCount: 0),
        .init(id: 45497910,
              name: "swift-evolution",
              fullName: "apple/swift-evolution",
              owner:
                User(id: 10639145,
                     name: "apple",
                     avatarImagePath: "https://avatars.githubusercontent.com/u/10639145?v=4",
                     htmlPath: "https://github.com/apple"),
              starsCount: 13842,
              watchersCount: 13842,
              forksCount: 2324,
              openIssuesCount: 27,
              language: "Markdown",
              htmlPath: "https://github.com/apple/swift-evolution",
              websitePath: "https://www.swift.org/swift-evolution/",
              description: "This maintains proposals for changes and user-visible enhancements to the Swift Programming Language.",
              subscribersCount: 0),
        .init(id: 4044891,
              name: "realm-swift",
              fullName: "realm/realm-swift",
              owner:
                User(id: 7575099,
                     name: "realm",
                     avatarImagePath: "https://avatars.githubusercontent.com/u/7575099?v=4",
                     htmlPath: "https://github.com/realm"),
              starsCount: 15661,
              watchersCount: 15661,
              forksCount: 2113,
              openIssuesCount: 399,
              language: "Objective-C",
              htmlPath: "https://github.com/realm/realm-swift",
              websitePath: "https://realm.io",
              description: "Realm is a mobile database: a replacement for Core Data & SQLite",
              subscribersCount: 0),
        .init(id: 56840338,
              name: "SwiftOCR",
              fullName: "NMAC427/SwiftOCR",
              owner:
                User(id: 9914734,
                     name: "NMAC427",
                     avatarImagePath: "https://avatars.githubusercontent.com/u/9914734?v=4",
                     htmlPath: "https://github.com/NMAC427"),
              starsCount: 4525,
              watchersCount: 4525,
              forksCount: 489,
              openIssuesCount: 86,
              language: "Swift",
              htmlPath: "https://github.com/NMAC427/SwiftOCR",
              websitePath: "",
              description: "Fast and simple OCR library written in Swift",
              subscribersCount: 0),
        .init(id: 47025785,
              name: "SwiftyBeaver",
              fullName: "SwiftyBeaver/SwiftyBeaver",
              owner:
                User(id: 16286228,
                     name: "SwiftyBeaver",
                     avatarImagePath: "https://avatars.githubusercontent.com/u/16286228?v=4",
                     htmlPath: "https://github.com/SwiftyBeaver"),
              starsCount: 5593,
              watchersCount: 5593,
              forksCount: 443,
              openIssuesCount: 1,
              language: "Swift",
              htmlPath: "https://github.com/SwiftyBeaver/SwiftyBeaver",
              websitePath: "https://swiftybeaver.com",
              description: "Convenient & secure logging during development & release in Swift 4 & 5",
              subscribersCount: 0),
        .init(id: 190082368,
              name: "SwiftUI",
              fullName: "Jinxiansen/SwiftUI",
              owner:
                User(id: 16829428,
                     name: "Jinxiansen",
                     avatarImagePath: "https://avatars.githubusercontent.com/u/16829428?v=4",
                     htmlPath: "https://github.com/Jinxiansen"),
              starsCount: 4470,
              watchersCount: 4470,
              forksCount: 468,
              openIssuesCount: 0,
              language: "Swift",
              htmlPath: "https://github.com/Jinxiansen/SwiftUI",
              websitePath: "https://jinxiansen.github.io/SwiftUI/",
              description: "`SwiftUI` Framework  Learning and Usage Guide. 🚀 ",
              subscribersCount: 0),
        .init(id: 130471182,
              name: "SwiftEntryKit",
              fullName: "huri000/SwiftEntryKit",
              owner:
                User(id: 5504255,
                     name: "huri000",
                     avatarImagePath: "https://avatars.githubusercontent.com/u/5504255?v=4",
                     htmlPath: "https://github.com/huri000"),
              starsCount: 6052,
              watchersCount: 6052,
              forksCount: 539,
              openIssuesCount: 64,
              language: "Swift",
              htmlPath: "https://github.com/huri000/SwiftEntryKit",
              websitePath: "",
              description: "SwiftEntryKit is a presentation library for iOS. It can be used to easily display overlays within your iOS apps.",
              subscribersCount: 0),
        .init(id: 190211663,
              name: "SwiftUI",
              fullName: "ivanvorobei/SwiftUI",
              owner:
                User(id: 10995774,
                     name: "ivanvorobei",
                     avatarImagePath: "https://avatars.githubusercontent.com/u/10995774?v=4",
                     htmlPath: "https://github.com/ivanvorobei"),
              starsCount: 4118,
              watchersCount: 4118,
              forksCount: 454,
              openIssuesCount: 3,
              language: "Swift",
              htmlPath: "https://github.com/ivanvorobei/SwiftUI",
              websitePath: "https://opensource.ivanvorobei.by",
              description: "Examples projects using SwiftUI released by WWDC2019. Include Layout, UI, Animations, Gestures, Draw and Data.",
              subscribersCount: 0)
    ]
}

/*
 e.g.
 .onAppear {
     var message = ""
     for repo in repos {
         message += repo.createInitializerString()
         message += "\n"
     }
     print(message)
 }
 */
/// sampleDataの作成用のデバッグ関数
extension Repo {
    
    func createInitializerString() -> String {
        """
.init(id: \(id),
      name: "\(name)",
      fullName: "\(fullName)",
      owner:
        User(id: \(owner.id),
             name: "\(owner.name)",
             avatarImagePath: "\(owner.avatarImagePath)",
             htmlPath: "\(owner.htmlPath)"),
      starsCount: \(starsCount),
      watchersCount: \(watchersCount),
      forksCount: \(forksCount),
      openIssuesCount: \(openIssuesCount),
      language: "\(language ?? "")",
      htmlPath: "\(htmlPath)",
      websitePath: "\(websitePath ?? "")",
      description: "\(description ?? "")",
      subscribersCount: \(subscribersCount ?? 0)),
"""
    }
}
